# -*- coding: utf-8 -*-
"""langchain_academy_l5_memory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3RNCH-nAKrd2xHmGqATOHATSQ2Bxz-U
"""

!pip install langchain-community

from langchain_community.utilities import SQLDatabase
db = SQLDatabase.from_uri("sqlite:///Chinook.db")

from dataclasses import dataclass

# 런타임에 접근할 수 있도록 데이터베이스에 런타임 컨텍스트 정의
@dataclass
class RuntimeContext:
  db: SQLDatabase

!pip install langchain-google-genai

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

from langchain_core.tools import tool
from langgraph.runtime import get_runtime

@tool
def execute_sql(query: str) -> str:
  """Execute a SQLite command and return result."""
  runtime = get_runtime(RuntimeContext)
  db = runtime.context.db

  try:
    return db.run(query)
  except Exception as e:
    return f"Error: {e}"

SYSTEM_PROMPT = """You are a careful SQLite analyst.

Rules:
- Tink step-by-step.
- When you need data, call the tool `execute_sql` with ONE SELECT query.
- Read-only only; no INSERT/UPDATE/DELETE/ALTER/DROP/CREATE/REPLACE/TRUNCATE.
- Limit to 5 rows unless the user explicitly asks otherwise.
- If the tool returns 'Error:', revise the SQL and try again.
- Prefer explicit column lists; avoid SELECT *.
"""

from langchain.agents import create_agent
from langchain_core.messages import SystemMessage

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[execute_sql],
    system_prompt=SYSTEM_PROMPT,
    context_schema=RuntimeContext,
)

"""## Repeated Queries"""

!wget -q https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite -O Chinook.db

question = "This is Frank Harris, What was the total on my last invoice?"
steps = []

for step in agent.stream(
    {"messages": [{"role": "user", "content": question}]},
    stream_mode="values",
    context=RuntimeContext(db=db),
):
  step["messages"][-1].pretty_print()
  steps.append(step)

question = "What were the titles?"

for step in agent.stream(
    {"messages": [{"role": "user", "content": question}]},
    stream_mode="values",
    context=RuntimeContext(db=db),
):
  step["messages"][-1].pretty_print()

# 추론 불가. 대답 못함

"""## **Add memory**"""

from langgraph.checkpoint.memory import InMemorySaver

from langchain.agents import create_agent
from langchain_core.messages import SystemMessage

agent = creat_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[execute_sql],
    system_prompt=SYSTEM_PROMPT,
    context_schema=RuntimeContext,
    memory=InMemorySaver(), # 에이전트에 체크포인트(일종의 단기 메모리) 추가
)

question = "This is Frank Harris, What was the total on my last invoice?"
steps = []

for step in agent.stream(
    {"messages": [{"role": "user", "content": question}]},
    {"configurable": {"thread_id": "1"}}, # 중요! 스레드id를 전달. 특정 스레드의 상태를 추적할 수 있도록 보장
    stream_mode="values",
    context=RuntimeContext(db=db),
):
  step["messages"][-1].pretty_print()

question = "What were the titles?"

for step in agent.stream(
    {"messages": [{"role": "user", "content": question}]},
    {"configurable": {"thread_id": "1"}}, # 컨텍스트를 이어갈 스레드id 전달
    stream_mode="values",
    context=RuntimeContext(db=db),
):
  step["messages"][-1].pretty_print()

# 대답과 깔끔한 요약까쥐