# -*- coding: utf-8 -*-
"""langchain_academy_l7_structured_output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwuQmgR19d5iV0ZEKhvX8mRFX4hZrBdo
"""

!pip install langchain-google-genai

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""# **Structured Output**"""

from typing import TypedDict
from langchain.agents import create_agent

class ContactInfo(TypedDict): # TypedDict로 출력
  name: str
  email: str
  phone: str

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    response_format=ContactInfo
)

recorded_conversation = """We talked with John Doe. He works over at Example.
His number is, let's see,
five, five, five, one two threee, four, five, six seven. Did you get that?
And, hist email was john at example.com. He wanted to order 50 boxes of Captain Crunch."""

result = agent.invoke(
    {"messages": [{"role": "user", "content": recorded_conversation}]}
)

result["structured_response"]

"""### **Multiple data types are suppored**

*   pydantic `BaseModel`
*   `TypedDict`
*   `dataclasses`
*   json schema (dict)


"""

from langchain.agents import create_agent
from pydantic import BaseModel

class ContactInfo(BaseModel): # ContactInfo 인스턴스 형태로 반환
  name: str
  email: str
  phone: str

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    response_format=ContactInfo
)

recorded_conversation = """We talked with John Doe. He works over at Example.
His number is, let's see,
five, five, five, one two threee, four, five, six seven. Did you get that?
And, hist email was john at example.com. He wanted to order 50 boxes of Captain Crunch."""

result = agent.invoke(
    {"messages": [{"role": "user", "content": recorded_conversation}]}
)

result["structured_response"]

