# -*- coding: utf-8 -*-
"""LangChain_Acedemy_L1_fast_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eu-3-iQZrx8Xs0GFIS-Rt42Panbw9d8O
"""

#!pip install langchain-community

from langchain_community.utilities import SQLDatabase
db = SQLDatabase.from_uri("sqlite:///Chinook.db")

from dataclasses import dataclass
from langchain_community.utilities import SQLDatabase

# 런타임에 접근할 수 있도록 데이터베이스에 런타임 컨텍스트 정의
@dataclass
class RuntimeContext:
  db: SQLDatabase

from langchain_core.tools import tool
from langgraph.runtime import get_runtime

@tool
def execute_sql(query: str) -> str:
  """Execute a SQLite command and return results."""
  runtime = get_runtime(RuntimeContext) # DB가 연결된 런타인 컨텍스트 정보를 가져오는 함수 get_runtime

  try:
    return db.run(query)
  except Exception as e:
    return f"Error: {e}"

SYSTEM_PROMPT = """ You are a careful SQLite analyst.

Rules:
- Think step-by-step.
- When you need data, call the tool `execute_sql` with ONE SELECT query.
- Read-only only; no INSERT/UPDATE/DELETE/ALTER/DROP/CREATE/REPLACE/TRUNCATE.
- Limit to 5 rows of output unless the user explicitly asks otherwise.
- If the tool returns 'Error:', revise the SQL and try again.
- Prefer explicit column lists; avoid SELECT *.
"""

#!pip install langchain-google-genai

#import os
#from google.colab import userdata
#os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

from langchain.agents import create_agent

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[execute_sql],
    system_prompt=SYSTEM_PROMPT,
    context_schema=RuntimeContext
)

#from IPython.display import Image, display
#display(Image(agent.get_graph(xray=True).draw_mermaid_png()))

# 💡 NOTICE
# 에이전트는 데이터베이스 스키마에 접근할 수 없다 - SQL 쿼리를 통해 독립적으로 실행해야 함
# 에이전트는 실수할 수 있다 - 에러 메시지를 반환함으로써, 해당 에러에 응답하여 스스로 쿼리 수정 가능
# 에이전트는 호출 사이에 스키마를 기억하지 못한다 - 나중에 메모리를 사용하여 제어

question = "Which table has the largets number of entries?"

for step in agent.stream(
    {"messages": question},
    context=RuntimeContext(db=db),
    stream_mode="values",
):
  step["messages"][-1].pretty_print()

question = "Which genre on average has the longest tracks?"

for step in agent.stream(
    {"messages": question},
    context=RuntimeContext(db=db),
    steram_mode="values"
):
  step["messages"][-1].pretty_print()

# genre라는 테이블이 없어서 에러 발생 - 테이블 스키마를 기억하지 못한다
# 스스로 쿼리를 수정해 Genre 테이블로 다시 쿼리

