# -*- coding: utf-8 -*-
"""langchain_academy_l5_tools_with_mcp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFwFUIYKbUC-AcmFhNmx3MHQ4Bd6UeT2
"""

!pip install langchain-google-genai

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""# Tool with MCP"""

!pip install -q langchain-mcp-adapters

import sys, os
sys.stderr = open(os.devnull, "w")

from langchain_mcp_adapters.client import MultiServerMCPClient
import nest_asyncio

nest_asyncio.apply()

mcp_client = MultiServerMCPClient(
    {
        "time": {
            "transport": "stdio",
            "command": "npx",
            "args": ["-y", "@theo.foobar/mcp-time"],
        }
    },
)

# Load tools from the MCP server
mcp_tools = await mcp_client.get_tools()
print(f"Loaded {len(mcp_tools)} MCP tools: {[t.name for t in mcp_tools]}")

from langchain.agents import create_agent

agent_with_mcp = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=mcp_tools,
    system_prompt="You are a helpful assistant",
)

result = await agent_with_mcp.ainvoke(
    {"messages": [{"role": "user", "content": "What's the current time in San Francisco right now?"}]}
)

for msg in result["messages"]:
  msg.pretty_print()

