# -*- coding: utf-8 -*-
"""LangChain_Acedemy_L3_streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk4nwkfs1UGjuyfM8nCBcB5lgO84FZFV
"""

#!pip install langchain-google-genai
#
#import os
#from google.colab import userdata
#
#os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""# Streaming"""

from langchain.agents import create_agent

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    system_prompt="You are a full-stack comedian"
)

"""## No Streaming(invoke)"""

result = agent.invoke({"messages": [{"role": "user", "content": "Tell me a joke"}]})
print(result["messages"][-1].content)

"""## values 값 스트리밍 모드
에이전트 루프의 각 단계 후에 데이터를 스트리밍

모델과 도구 호출 후에 업데이트를 기대
"""

# Stream = values
for step in agent.stream(
    {"messages": [{"role": "user", "content": "Tell me a Dad joke"}]},
    stream_mode="values"
):
  step["messages"][-1].pretty_print()

"""## messages

데이터를 토큰단위로 스트림하여 최저 지연시간으로 응답

챗봇같은 인터랙티브 애플리케이션에 적합

"""

for token, metadata in agent.stream(
    {"messages": [{"role": "user", "content": "Write me a family friendly poem."}]},
    stream_mode="messages"
):
  print(f"{token.content}", end="")

# ChatGPT나 Claude 같이 응답이 오는대로 표시

"""## Tools can stream too
도구에서도 스트리밍할 수 있다
"""

from langchain.agents import create_agent
from langgraph.config import get_stream_writer

def get_weather(city: str) -> str:
  """Get weather for a given city."""
  writer = get_stream_writer()
  # stream any arbitrary data
  writer(f"Looking up data for city: {city}")
  writer(f"Acquired data for city: {city}")
  return f"It's always sunny in {city}"

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[get_weather]
)

for chunk in agent.stream(
    {"messages": [{"role": "user", "content": "What is the wather in SF?"}]},
    stream_mode=["values", "custom"] # 값모드랑 커스텀 모드를 모두 사용해 스트리밍
):
  print(chunk)

