# -*- coding: utf-8 -*-
"""langchain_academy_l4_tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LQEzBJdofH1LleKbenMDDse2RA64frr
"""

!pip install langchain-google-genai

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""# Tools
## Calculator example
"""

from typing import Literal
from langchain.tools import tool

@tool
def real_number_calculator(
    a: float, b: float, operation: Literal["add", "subtract", "multiply", "divide"]
) -> float:
  """Perform basic arithmetic operations on two real numbers."""
  print("🧮 Invoking calculator tool")
  #Perform the specified operation
  if operation == "add":
    return a + b
  elif operation == "subtract":
    return a - b
  elif operation == "multiply":
    return a * b
  elif operation == "divide":
    if b == 0:
      raise ValueError("Division by zero is not allowed.")
    return a / b
  else:
    raise ValueError(f"Invalid oepration: {operation}")

from langchain.agents import create_agent

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[real_number_calculator],
    system_prompt="You are a helpful assistant",
)

result = agent.invoke(
    {"messages": [{"role": "user", "content": "What is 3.1125 * 4.1234"}]}
)
print(result["messages"][-1].content)

result = agent.invoke({"messages": [{"role": "user", "content": "What is 3 * 4"}]})
print(result["messages"][-1].content)

result = agent.invoke({"messages": [{"role": "user", "content": "What is 3.0 * 4.0"}]})
print(result["messages"][-1].content)

"""## Adding a more detailed description
위 예제에서 제공한 계산기툴을 사용하지 않고, llm이 계산해버릴 수도 있음

@tool 인수에 상세 설명을 추가해보자
"""

from typing import Literal
from langchain.tools import tool

@tool(
    "calculator",
    parse_docstring=True, # docstring을 Google-style로 파싱해서 인자별 설명까지 LLM에 전달하는 옵션
    description=(
        "Perform basic arithmetic operations on two real numbers."
        "Use this whenever you have operations on any numbers, even if they are integers."
    ),
)

def real_number_calculator(
    a: float, b: float, operation: Literal["add", "subtract", "multiply", "divide"]
) -> float:

  # docstring
  """Perform basic arithmetic operations on two real numbers.

  Args:
    a (float): The first number.
    b (float): The second number.
    operation (Literal["add", "subtract", "multiply", "divide"]):
      The arithmetic operation to perform.

      - `"add"`: Returns the sum of `a` and `b`.
      - `"subtract"`: Returns the result of `a - b`.
      - `"multiply"`: Returns the product of `a` and `b`.
      - `"divide"`: Returns the result of `a / b`. Raises an error if `b` is zero.

  Returns:
    float: The numerical result of the specified operation.

  Raieses:
    ValueError: If an invalid operation is provided or division by zero is attempted.
  """
  print("Invoking calculator tool")
  #Perform the specified operation
  if operation == "add":
    return a + b
  elif operation == "subtract":
    return a - b
  elif operation == "multiply":
    return a * b
  elif operation == "divide":
    if b == 0:
      raise ValueError("Division by zero is not allowed.")
    return a / b
  else:
    raise ValueError(f"Invalid oepration: {operation}")

"""## **parse_docstring=False(기본)**

```
  @tool
  
  def calculator(a: float, b: float, op: str) -> float:
      '''두 수에 대한 연산을 수행합니다.
      

      Args:
          a: 첫 번째 피연산자
          b: 두 번째 피연산자
          op: '+', '-', '*', '/' 중 하나
      '''
      ...
```

  LLM이 보는 정보:
  - description: docstring 전체가 그대로 들어감 (Args 섹션 포함, 그냥 한 덩어리 텍스트)
  - args: a (float), b (float), op (str) — 타입만 있고 개별 설명은 없음
  
---
## **parse_docstring=True**

```
  @tool(parse_docstring=True)
         
  def calculator(a: float, b: float, op: str) -> float:
  
      '''두 수에 대한 연산을 수행합니다.
      

      Args:
          a: 첫 번째 피연산자
          b: 두 번째 피연산자
          op: '+', '-', '*', '/' 중 하나
      '''
      ...
```

  LLM이 보는 정보:

  - description: "두 수에 대한 연산을 수행합니다." (요약만)
  - args 스키마:
    - a: 첫 번째 피연산자
    - b: 두 번째 피연산자
    - op: '+', '-', '*', '/' 중 하나
"""

from langchain.agents import create_agent

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[real_number_calculator],
    system_prompt="You are a helpful assistant",
)

result = agent.invoke({"messages": [{"role": "user", "content": "What is 3.0 * 4.0"}]})
print(result["messages"][-1].content)

result = agent.invoke({"messages": [{"role": "user", "content": "What is 3 * 4"}]})
print(result["messages"][-1].content)

