# -*- coding: utf-8 -*-
"""LangChain_Acedemy_L2_messages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2ecNlO2GrbZj6jCED133HDH4fQtysls
"""

#!pip install langchain-google-genai
#
#import os
#from google.colab import userdata
#
#os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

"""# 💌 Human and AI Messages"""

from langchain.agents import create_agent
from langchain_core.messages import HumanMessage

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    system_prompt="You are a full-stack comedian"
)

human_msg = HumanMessage("Hello, how are you?")
result = agent.invoke({"messages": [human_msg]})

print(result["messages"][-1].content)

print(type(result["messages"][-1]))

for msg in result["messages"]:
  print(f"{msg.type}: {msg.content}\n")

"""## Alternative formats
### Strings
"""

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    system_prompt="You are a terse sports poet"
)

result = agent.invoke({"messages": "Tell me about baseball"})
print(result["messages"][-1].content)

"""### Dictionaries"""

result = agent.invoke(
    {"messages": {"role": "user", "content": "Write a haiku about sprinters"}}
)
print(result["messages"][-1].content)

"""# Output Format
### messages
"""

from langchain_core.tools import tool

# 시(haiku)가 3줄인지 체크하고, 여부에 따라 메시지를 출력하게 하는 도구
@tool
def check_haiku_lines(text: str):
  """Check if the given haiku text has exactly 3 lines.

  Return None if it's correct, otherwise an error message.
  """

  # Split the text into lines, ignoring leading/trailing spaces
  lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
  print(f"checking haiku, it has {len(lines)} lines: \n {text}")

  if len(lines) != 3:
    return f"Incorrect! This haiku has {len(lines)} lines. A haiku must have exactly 3 lines."
  return "Correct, this haiku has 3 lines."

agent = create_agent(
    model="google_genai:gemini-2.5-flash",
    tools=[check_haiku_lines],
    system_prompt="You are a sports poet who only writes Haiku. You always check your work."
)

result = agent.invoke({"messages": "Please write me a poem."})

result["messages"][-1].content

print(len(result["messages"]))

for i, msg in enumerate(result["messages"]):
  msg.pretty_print()

"""## Other useful information"""

result

result["messages"][-1]

result["messages"][-1].usage_metadata

result["messages"][-1].response_metadata

